# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""
Django settings for qcon project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Secrets loader: prefer files in /etc/secrets/{name}, fall back to env vars
SECRETS_DIR = Path("/etc/secrets")

def get_secret(name: str, default: str = None, required: bool = False, subdirectory: str = None) -> str:
    """
    Load a secret from /etc/secrets/{name} if present, otherwise from environment.
    Strips trailing whitespace. If required and missing, raise an error.
    """
    base_dir = SECRETS_DIR / subdirectory if subdirectory else SECRETS_DIR
    file_path = base_dir / name
    if file_path.exists():
        val = file_path.read_text(encoding="utf-8").strip()
    else:
        val = os.getenv(name, default)

    if required and (val is None or val == ""):
        raise RuntimeError(
            f"Missing required secret: {name} (file {file_path} or env var {name})"
        )

    return val

# mandatory vars
ADMIN_USERNAME = get_secret('ADMIN_USERNAME', subdirectory='app-internal-credentials', required=True)
ADMIN_PASSWORD = get_secret('ADMIN_PASSWORD', subdirectory='app-internal-credentials', required=True)
POSTGRES_HOST = get_secret('POSTGRES_HOST', subdirectory='db-credentials', required=True)
API_KEY = get_secret('API_KEY', subdirectory='api-key', required=True)

DYNAMIC_DB_CREDENTIAL_DIR = os.getenv('DYNAMIC_DB_CREDENTIAL_DIR', '/etc/secrets/db-credentials')
DYNAMIC_DB_CREDENTIALS_REQUIRED = os.getenv(
    'DYNAMIC_DB_CREDENTIALS_REQUIRED',
    'false' if os.getenv('DEBUG', False) == 'true' else 'true',
) == 'true'

# optional vars
APP_VERSION = os.getenv('APP_VERSION', default='')
IMAGE_TAG = os.getenv('IMAGE_TAG', default='')
IMAGE_NAME = os.getenv('IMAGE_NAME', default='')
 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# Defaults in `.secrets`
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret("DJANGO_SECRET_KEY", subdirectory='app-internal-credentials', required=True)

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv('DEBUG', False) == 'true'
ADMIN_ENABLED = os.getenv('DEBUG', False) == 'true'
LOGGING_LEVEL = 'INFO'

if DEBUG:
    LOGGING_LEVEL = 'DEBUG'
    
ALLOWED_HOSTS = ['*']

CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-Party Apps
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'channels',

    # Local Apps
    'api',
    'restapi'
]

 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qcon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'qcon.wsgi.application'

# Channels
ASGI_APPLICATION = 'qcon.asgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'qcon.db_backends.postgresql_dynamic',
        'NAME': get_secret("POSTGRES_DB", subdirectory='db-credentials', required=True),
        'USER': get_secret("POSTGRES_USER", subdirectory='db-credentials', required=True),
        'PASSWORD': get_secret("POSTGRES_PASSWORD", subdirectory='db-credentials', required=True),
        'HOST': POSTGRES_HOST,
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler'
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/html/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'tmp/')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'verbose': {
            'format':
            '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'custom': {
            'format': '{levelname} {asctime} {name} {funcName} {message}',
            'style': '{',
        }
    },
    'handlers': {
        'console': {
            'level': LOGGING_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'custom'
        },
        'celery': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'celery.log',
            'formatter': 'custom',
            'maxBytes': 1024 * 1024 * 10,  # 10 mb
            'filters': ['require_debug_true']
        },
        'console_dev': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'dev.log',
            'formatter': 'custom',
            'maxBytes': 1024 * 1024 * 10,  # 10 mb
            'filters': ['require_debug_true']
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console','console_dev'],
            'level': 'ERROR',
            'propagate': False,
        },
        'api': {
            'handlers': ['console','console_dev'],
            'level': LOGGING_LEVEL,
            'propagate': False,
        },
        # 'celery': {
        #     'handlers': ['console'],
        #     'level': 'DEBUG',
        #     'propagate': True,
        # },
        'celery.task': {
            'handlers': ['console','console_dev','celery'],
            'level': 'DEBUG',
            'propagate': False
        }
    },
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        # 'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        # 'api_v2.authentication.ExampleAuthentication',
    ]
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Celery settings
CELERY_BROKER_URL = "redis://localhost:6379"
CELERY_RESULT_BACKEND = "redis://localhost:6379"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
    }
}
